### ISSUE TITLE
PlotTopologies always uses default reference frame

### ISSUE THREAD

**Issue by thomas-schouten** [GPlates/gplately#112]
Hi,

When I try to plot the resolved plate topologies of a reconstruction (say Clennett et al., 2020) at a given time (say 130 Ma), I am unable to modify the reference frame. Below is my code. The resulting figure (attached) shows that the two topologies overlap exactly, whereas given the relative motion between North America and India, we would expect the resolved topologies to be rotated relative to one another. I would like to show my reconstruction in a palaeomagnetic reference frame (i.e. absolute latitude) vs. a mantle reference frame (latitude and longitude relative to the mantle) or relative to any continent. Am I missing something or is this simply not possible to plot in a difference reference frame in gplately?

Many thanks,
Thomas

```
import gplately
import geopandas as gpd
import matplotlib.pyplot as plt 
import cartopy.crs as ccrs

gdownload = gplately.download.DataServer("Clennett2020")
C2020_rotation_file, C2020_topology_features, C2020_static_polygons = gdownload.get_plate_reconstruction_files()

C2020 = gplately.PlateReconstruction(C2020_rotation_file, C2020_topology_features, C2020_static_polygons)

gplot501 = gplately.PlotTopologies(C2020, anchor_plate_id=501, time=130)
gplot101 = gplately.PlotTopologies(C2020, anchor_plate_id=101, time=130)

fig, ax = plt.subplots(subplot_kw={"projection": ccrs.Robinson()}, dpi=300)

gplot501.plot_all_topologies(ax=ax)
gplot101.plot_all_topologies(ax=ax)
```

![image](https://github.com/GPlates/gplately/assets/130984647/309cf2d0-5c1c-44a7-afad-948f4dd60e77)

**Comment by michaelchin** [comment]
Just had a quick look at the code. It seemed the anchor plate id was not passed into the lower function call. 

https://github.com/GPlates/gplately/blob/5cd69ac81e65f7feee057620542ca0076f41c0a9/gplately/plot.py#L1048-L1051

**Comment by michaelchin** [comment]
I have fixed the problem. You need to re-install gplately from source code and use the modified test script https://github.com/GPlates/gplately/blob/master/unittest/test_anchor_plate_id.py

![Figure_1](https://github.com/GPlates/gplately/assets/2688316/c2d86a17-872b-4b8e-8076-e59777b67185)

**Comment by brmather** [comment]
I've also made updates to the `gplately.PlateReconstruction` and `gplately.Points` object to use non-zero anchor plate IDs in #131
