### ISSUE TITLE
next release planner

### ISSUE THREAD

**Issue by michaelchin** [GPlates/gplately#120]
version number: 2.0
release date: before the end of 2023
what to include: "plate model manager", "bug fixes", ...

This is a place to keep records of planning next GPlately release.

**Comment by brmather** [comment]
How about we release version 2 after we migrate all the download server files to your new download manager? Dietmar has recently hired an RA who will put the plate reconstruction models on Zenodo, and the age grids + spreading rate grids to NCI. I think this is probably achievable by early December... what do you think?

**Comment by michaelchin** [comment]
> How about we release version 2 after we migrate all the download server files to your new download manager? Dietmar has recently hired an RA who will put the plate reconstruction models on Zenodo, and the age grids + spreading rate grids to NCI. I think this is probably achievable by early December... what do you think?

Sounds good.

**Comment by brmather** [comment]
I have to create a point release for a STELLAR deliverable. Just letting you know.

**Comment by michaelchin** [comment]
"release candidate" releases --  Wednesday 20 Dec, 2023
2.0 official release -- Friday 22 Dec, 2023

**Comment by michaelchin** [comment]
This Issue is obsolete. Close this one and open a new one for 2.0 release.
