### ISSUE TITLE
Muller 2022 Plate model 

### ISSUE THREAD

**Issue by ARutson** [GPlates/gplately#127]
Hello All,
The plate model for Muller2022 and Merdith2021 from the datacentre come out as the same (see first 2 Images), with some variations in how they get the coastline, continent, and CoB polygons. 

There are additional rotation files in the earthbyte model downloads for Muller2022, with an optimised Merdith2021 and a no-net rotation.rot files (see Image 3 and 4 respectively). Looking at the Muller 2022 paper, it looks like the optimised Merdith2021 is the one they use to produce the images in their paper.

Image 1  (Merdith2021 from data server)
![merdith2021_datacentre](https://github.com/GPlates/gplately/assets/98044971/d3a448fe-502e-48eb-a3d3-cb4fd36166d5)
Image 2 (Merdith2021 from data server)
![Muller2022_datacentre](https://github.com/GPlates/gplately/assets/98044971/e713e353-5619-4273-be8e-b6e989e8df23)
Image 3 (Optimised Merdith2021 files from Muller2022 repository on EarthByte)
![Merdith2021_Optimised](https://github.com/GPlates/gplately/assets/98044971/9523eade-a8e2-4646-b1bb-93128d689936)
Image 4 (No Net rotation files from Muller2022 repository on EarthByte)
![Muller2022_local](https://github.com/GPlates/gplately/assets/98044971/3b2e29db-bf4a-4455-8bbb-2d28ff7adc54)

**Comment by michaelchin** [comment]
Hi @ARutson ,

We have updated the Muller2022 model. Could you please send us the code to plot the above maps? We would like to do some testings before closing this Issue. Thanks.

**Comment by ARutson** [comment]
Hi @michaelchin ,

Sorry for the delay. Here s the script for generating the images above. For the local file names I've renamed the directory paths so you can enter your own into it, if needs be.

[Gplately_Plate_Files_Test.txt](https://github.com/GPlates/gplately/files/13425116/Gplately_Plate_Files_Test.txt)


Kind regards,
Alex

**Comment by michaelchin** [comment]
> Hi @michaelchin ,
> 
> Sorry for the delay. Here s the script for generating the images above. For the local file names I've renamed the directory paths so you can enter your own into it, if needs be.
> 
> [Gplately_Plate_Files_Test.txt](https://github.com/GPlates/gplately/files/13425116/Gplately_Plate_Files_Test.txt)
> 
> Kind regards, Alex

Thanks Alex.  Here is the test result. You need to install gplately from github repository to use the latest changes.

<img width="1319" alt="Screenshot 2023-11-22 at 6 24 08 pm" src="https://github.com/GPlates/gplately/assets/2688316/6b2295b6-dc6d-408b-aead-afe76a59ebde">
