### ISSUE TITLE
Add Plate Tectonic Tools command line as gplately subcommands

### ISSUE THREAD

**Issue by michaelchin** [GPlates/gplately#129]
fix_crossovers and remove_plate_rotations have been done in  da681cf0a61abe4fa89d401466a58bb3529d6bf6

**Comment by michaelchin** [comment]
Hi @jcannon-gplates ,

I will gradually add Plate Tectonic Tools commands into gplately as subcommands. Two of them have been done - fix-crossovers and remove-plate-rotations. See the code below. Let me know if you have any concerns or anything I should pay attention to. Thanks.

https://github.com/GPlates/gplately/blob/9a751e98ff1aff5869fe2eb6f400f490bb815c39/gplately/__main__.py#L156-L170

**Comment by jcannon-gplates** [comment]
That looks good!

I can confirm that `python -m gplately fix_crossovers -d -c 0.01 rotations.rot` worked as intended.

So it looks like the following PlateTectonicTools commands remain (ie, the only ones with command-line options):
- [cleanup_topologies.py](https://github.com/EarthByte/PlateTectonicTools/blob/master/ptt/cleanup_topologies.py)
- [convert_xy_to_gplates.py](https://github.com/EarthByte/PlateTectonicTools/blob/master/ptt/convert_xy_to_gplates.py)
- [diagnose_rotations.py](https://github.com/EarthByte/PlateTectonicTools/blob/master/ptt/diagnose_rotations.py)
- [resolve_topologies.py](https://github.com/EarthByte/PlateTectonicTools/blob/master/ptt/resolve_topologies.py)
- [rotation_tools.py](https://github.com/EarthByte/PlateTectonicTools/blob/master/ptt/rotation_tools.py)
- [separate_ridge_transform_segments.py](https://github.com/EarthByte/PlateTectonicTools/blob/master/ptt/separate_ridge_transform_segments.py)
- [subduction_convergence.py](https://github.com/EarthByte/PlateTectonicTools/blob/master/ptt/subduction_convergence.py)

Thanks!

**Comment by michaelchin** [comment]
> That looks good!
> 
> I can confirm that `python -m gplately fix_crossovers -d -c 0.01 rotations.rot` worked as intended.
> 
> So it looks like the following PlateTectonicTools commands remain (ie, the only ones with command-line options):
> 
> * [cleanup_topologies.py](https://github.com/EarthByte/PlateTectonicTools/blob/master/ptt/cleanup_topologies.py)
> * [convert_xy_to_gplates.py](https://github.com/EarthByte/PlateTectonicTools/blob/master/ptt/convert_xy_to_gplates.py)
> * [diagnose_rotations.py](https://github.com/EarthByte/PlateTectonicTools/blob/master/ptt/diagnose_rotations.py)
> * [resolve_topologies.py](https://github.com/EarthByte/PlateTectonicTools/blob/master/ptt/resolve_topologies.py)
> * [rotation_tools.py](https://github.com/EarthByte/PlateTectonicTools/blob/master/ptt/rotation_tools.py)
> * [separate_ridge_transform_segments.py](https://github.com/EarthByte/PlateTectonicTools/blob/master/ptt/separate_ridge_transform_segments.py)
> * [subduction_convergence.py](https://github.com/EarthByte/PlateTectonicTools/blob/master/ptt/subduction_convergence.py)
> 
> Thanks!

Thanks @jcannon-gplates 

In my Conda environment, the `python -m` part is not needed. Simply `gplately fix_crossovers -d -c 0.01 rotations.rot` works.

**Comment by jcannon-gplates** [comment]
> In my Conda environment, the `python -m` part is not needed. Simply `gplately fix_crossovers -d -c 0.01 rotations.rot` works.

Interesting, thanks, that works for me too.

An interesting side observation on Windows: before I upgraded my conda environment to gplately 1.1, typing `gplately --version` in my conda env would find the `gplately 1.1` installed via pip into a non-conda Python (since there was a `gplately.exe` in `Python\Scripts` which is in PATH) whereas `python -m gplately --version` would look up the conda gplately only (which, before upgrading to 1.1, would understandably fail with `No module named gplately.__main__; 'gplately' is a package and cannot be directly executed` - but would work when upgraded to 1.1). But once upgrading to 1.1 this becomes a non-issue since a conda environment always puts itself first in the PATH.

**Comment by michaelchin** [comment]
> would understandably fail with `No module named gplately.__main__; 'gplately' is a package and cannot be directly executed` - but would work when upgraded to 1.1).

I added gplately.__main__; after gplately 1.0.

It is here 
https://github.com/GPlates/gplately/blob/181c058d843c35628669a60b6098b850dfb91868/pyproject.toml#L53-L54

**Comment by jcannon-gplates** [comment]
Thanks, yes I saw that. Just noting that some subtle differences between using and not using `python -m` can occasionally happen (especially on Windows) - which is why I tend to prefer `python -m` (even though it's more verbose).
