### ISSUE TITLE
Create a `pyproject.toml` next to setup.py

### ISSUE THREAD

**Issue by brmather** [GPlates/gplately#140]
Apparently `pyproject.toml` files are going to become the new standard for python packages. Currently `setup.py` is still [recommended to stay](https://packaging.python.org/en/latest/guides/modernize-setup-py-project/), but there are some advantages to the new packaging system - build time dependencies in particular!

It would be good to grab the version number from the current git tag at build time. I found this [python-versioneer](https://github.com/python-versioneer/python-versioneer) package that might be able to do this. Could you look into it, @michaelchin? I always accidentally release a package without updating the version number in `setup.py` which means it is not uploaded to PYPI or conda, and then I have to release another point release to fix my mistake...

**Comment by michaelchin** [comment]
https://packaging.python.org/en/latest/guides/single-sourcing-package-version/

**Comment by michaelchin** [comment]
I will create a script to update version, create tag, create release and publish to PyPI, usage example `./create-release.py 1.1.1`,

Basically copy these files from plate-model-manager project

- https://github.com/michaelchin/plate-model-manager/blob/main/scripts/create-release.py
- https://github.com/michaelchin/plate-model-manager/blob/main/scripts/pypi-publish.sh
- https://github.com/michaelchin/plate-model-manager/blob/main/.github/workflows/create-release.yml

Let me know if this look OK.

**Comment by brmather** [comment]
It would be preferable if this could be done via GitHub actions if we ever want to publish a new version of this software on JOSS. I also like to create new releases on GitHub because it can generate release notes that link to all the merged PRs. Is there a way to grab the version number from the tag and propagate that to setup.py?

**Comment by brmather** [comment]
Also, if I’m travelling and don’t have access to my computer it’s handy to create new releases on GitHub from my phone 😉
