### ISSUE TITLE
update gplately-feedstock meta.yaml

### ISSUE THREAD

**Issue by michaelchin** [GPlates/gplately#142]
Hi @brmather,

Shall we update the meta.yaml with latest one in gplately repo? Is there any magical automation to do it?
 
https://github.com/conda-forge/gplately-feedstock/blob/main/recipe/meta.yaml

**Comment by michaelchin** [comment]
This may/may not fix the circular import error on conda-forge

**Comment by brmather** [comment]
Good idea!

**Comment by michaelchin** [comment]
Hi @brmather

e62710247c5fc5a47a93468bfde17617bcc1003a might be able to fix the `import ptt` problem. Can you upload a new version to PyPI?

**Comment by brmather** [comment]
Just created a [v1.2.6 release](https://github.com/GPlates/gplately/releases/tag/v1.2.6). It should upload to PYPI shortly.

**Comment by michaelchin** [comment]
Done
