### ISSUE TITLE
possible indentation error

### ISSUE THREAD

**Issue by michaelchin** [GPlates/gplately#166]
It seems to me that the code below should be indented one more time

https://github.com/GPlates/gplately/blob/755af6dede02c336880feafe5d25a804c7e44abc/gplately/oceans.py#L1431-L1435

**Comment by jcannon-gplates** [comment]
Yes, I agree.

**Comment by michaelchin** [comment]
fixed in b071b2a72c061298a6a0d1384f94b404711b63bb
