### ISSUE TITLE
Add copyright and License info in source files? 

### ISSUE THREAD

**Issue by michaelchin** [GPlates/gplately#168]
like we did for ptt? 
discuss and decide

"""
    Copyright (C) 2023 The University of Sydney, Australia
    
    This program is free software; you can redistribute it and/or modify it under
    the terms of the GNU General Public License, version 2, as published by
    the Free Software Foundation.
    
    This program is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.
    
    You should have received a copy of the GNU General Public License along
    with this program; if not, write to Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
"""

**Comment by brmather** [comment]
Everything in quotation blocks is rendered by pdoc as documentation. Better to put hashtags there instead.

**Comment by michaelchin** [comment]
this should be done along with https://github.com/GPlates/gplately/issues/201

**Comment by michaelchin** [comment]
Done in 03f7540
