### ISSUE TITLE
refactor large source files?

### ISSUE THREAD

**Issue by michaelchin** [GPlates/gplately#169]
Some of the source files are growing too large(thousands of lines). Maybe consider to divide them into small files and add sub-folder when necessary.
consider, discuss and decide

**Comment by cpalfonso** [comment]
I came up with some improvements to the subduction teeth functions a while ago (such as specifying tooth size/spacing in points rather than projected units, as well as recalculating and redrawing the teeth when the extent of the plot changes) which involved some fairly extensive changes to the `gplately.plot` module, so I could have a look at breaking up that file when I implement those changes.

**Comment by michaelchin** [comment]
> I came up with some improvements to the subduction teeth functions a while ago (such as specifying tooth size/spacing in points rather than projected units, as well as recalculating and redrawing the teeth when the extent of the plot changes) which involved some fairly extensive changes to the `gplately.plot` module, so I could have a look at breaking up that file when I implement those changes.

Thanks, but no need to worry about it. I will take care of that.

**Comment by michaelchin** [comment]
> I came up with some improvements to the subduction teeth functions a while ago (such as specifying tooth size/spacing in points rather than projected units, as well as recalculating and redrawing the teeth when the extent of the plot changes) which involved some fairly extensive changes to the `gplately.plot` module, so I could have a look at breaking up that file when I implement those changes.

Hi @cpalfonso 

just out of curiosity, are you coming back to work on gplately? What's the plan?

@brmather

**Comment by michaelchin** [comment]
New pygplates will be released soon. The new GPlately release will follow soon. It is not a good time to refactor or touch working code. Put this issue on ice.

**Comment by michaelchin** [comment]
In fact, this issue is too broad and vague. It is a very bad example of creating github issues. It is even not good enough for a github Discussion. So, I will not even bother to convert this issue into a discussion.

I will close this issue. If some big source files are causing problems/pain, we should open new issues with specific info, such as which file, what problem, etc.

@michaelchin no offence, but I need to close this issue. -- XQ

**Comment by michaelchin** [comment]
> @michaelchin no offence, but I need to close this issue. -- XQ

None taken ;-)
