### ISSUE TITLE
Drop Python3.5 support

### ISSUE THREAD

**Issue by michaelchin** [GPlates/gplately#171]
@brmather  @lauren-ilano @laurilano 

The oldest Python version which is supported by the latest conda is 3.8. Should we drop python3.5? I really need to use f-string formatting.

<img width="804" alt="Screenshot 2024-04-05 at 12 33 34 PM" src="https://github.com/GPlates/gplately/assets/2688316/88c4c177-ba04-45b1-848c-5366e70d614b">

**Comment by brmather** [comment]
Go for it!

**Comment by michaelchin** [comment]
Hi @brmather  
I tried to add python3.12 support, but it seemed that I could not install stripy from conda-forge with python3.12. Any idea?
<img width="774" alt="Screenshot 2024-04-05 at 8 46 39 PM" src="https://github.com/GPlates/gplately/assets/2688316/83c3a227-656d-4f9a-adbf-865ff92bf1d8">

**Comment by brmather** [comment]
Stripy is stuck at 3.11 until I work out how to enable cross compilation with meson.

**Comment by michaelchin** [comment]
done in 446ee775117e377c62e7ba9e30622b49f96d4e6e
