### ISSUE TITLE
add a new plate model "Alfonso2024"

### ISSUE THREAD

**Issue by michaelchin** [GPlates/gplately#192]
The model files can be found at https://zenodo.org/records/11392269.

The model should be called "Alfonso2024".

**Comment by brmather** [comment]
Talk to Bianca (RA) about adding this on Zenodo

**Comment by michaelchin** [comment]
> The model files can be found at https://zenodo.org/records/11392269.

The model files can be found at https://zenodo.org/records/11392269.

**Comment by michaelchin** [comment]
> Talk to Bianca (RA) about adding this on Zenodo

The model files can be found at https://zenodo.org/records/11392269.

**Comment by michaelchin** [comment]
I have added the new model "alfonso2024" to the plate-model-manager https://github.com/michaelchin/plate-model-manager/commit/8569f4c86ae053d464f9d90364df98afdead8755. But the tests have not been completed yet. I will close this issue after finishing the tests.

**Comment by michaelchin** [comment]
I just wrote a test script and the new model "alfonso2024" looks fine.

<img width="1216" alt="Screenshot 2024-07-04 at 11 13 46 AM" src="https://github.com/GPlates/gplately/assets/2688316/450c8df7-fd77-490a-a2a9-1af38f82db5e">

**Comment by michaelchin** [comment]
<img width="578" alt="Screenshot 2024-07-04 at 11 16 20 AM" src="https://github.com/GPlates/gplately/assets/2688316/93656a0f-b97b-4f8e-a589-cb6777762b10">
<img width="741" alt="Screenshot 2024-07-04 at 11 17 38 AM" src="https://github.com/GPlates/gplately/assets/2688316/dc2a7bd9-1f13-458b-9a12-2683acef7048">

**Comment by michaelchin** [comment]
wait for 3 days to close this issue
pending close
