### ISSUE TITLE
What are the thin grey lines on the continents?

### ISSUE THREAD

**Issue by axelwang** [GPlates/gplately#194]
Hey. I am new to this package. I am noticing that, for example, in Notebook 1, "getting started", the continents (e.g. west US, central Asia etc) all have lots of thin grey lines on them, while in Muller's 2019 publication all continents do not have such features. What are these thin grey lines and how can I make them go away? Thanks!

**Comment by michaelchin** [comment]
The lines are the edges of polygons. You may set the colour of edges the same as the facecolor to make them disappear. 

<img width="926" alt="Screenshot 2024-06-17 at 4 45 01 PM" src="https://github.com/GPlates/gplately/assets/2688316/fd8e86af-2237-4ee6-ae09-a359753c4e8f">

**Comment by michaelchin** [comment]
Is this what you need?
<img width="1200" alt="Screenshot 2024-06-17 at 5 41 20 PM" src="https://github.com/GPlates/gplately/assets/2688316/2afec66d-7cbc-476f-9b04-0f9fc6a0f1e0">

**Comment by axelwang** [comment]
Exactly! Thank you!
