### ISSUE TITLE
gplately.pygplates.FeatureCollection is broken

### ISSUE THREAD

**Issue by michaelchin** [GPlates/gplately#195]
Hi @michaelchin, 

> Maybe we can modify and incorporate this unit test file in the automated Pytest cases.

You should absolutely add these tests to the automated testing. Is there any reason why all these tests are not run automatically using CI?

> The reason that the features were not pickled might be because the setstate and getstate functions were not implemented.

I'm just using `pygplates.FeatureCollection` at this stage.
There are still problems:

<img width="1060" alt="Screenshot 2024-06-17 at 9 29 36 AM" src="https://github.com/GPlates/gplately/assets/15915881/0cc7b7bb-643d-462e-a026-bba1f93db596">

1. It looks like filenames has become a global variable, appending multiple filenames from other `FeatureCollections`. Execute the same cell and the filenames are appended again.
2. The FeatureCollection is not properly loaded when you specify the filename using the filenames keyword. In my example above, if you set `gplot.time=0` and access the `gplot.COBs` attribute, you get a `None`.

As far as I can tell this object is completely broken. You should build and example on your machine and test a fix for this thoroughly. I say this because all of the workflows which make use of multiprocessing rely on this working. This is high priority stuff!

_Originally posted by @brmather in https://github.com/GPlates/gplately/issues/186#issuecomment-2172704370_

**Comment by michaelchin** [comment]
I tried to roll back my changes, but, unfortunately,  found the FeatureCollection class was even in worse condition before my code changes. Since the class is very simple and straightforward, I think we should fix it instead of rolling back to a much worse version.

**Comment by michaelchin** [comment]
I rolled back FeatureCollection class code changes to 2d6a98d02866cb4205d0e680087dbc0a75a029fd. All my recent changes on FeatureCollection class have been dropped. Since the new pygplates will come out soon, the gplately/pygplates.py will be removed after the new pygplates release. We should not waste too much time on the FeatureCollection class.

@brmather let me know if the rollback has fixed your problems. Thanks.

**Comment by michaelchin** [comment]
> I tried to roll back my changes, but, unfortunately, found the FeatureCollection class was even in worse condition before my code changes. Since the class is very simple and straightforward, I think we should fix it instead of rolling back to a much worse version.

No, we should not waster time to fix the new code. Simply roll back the code changes and wait for new pygplates release to get rid of pygplates.py.

**Comment by michaelchin** [comment]
Rollback has been completed in 2d6a98d02866cb4205d0e680087dbc0a75a029fd and 25c75cd36448f4bafb0977c6b597c625beb0c6f4. I will close this issue in 7 days if no further problems are reported. Unpin this issue and downgrade the priority to 'medium'.

**Comment by michaelchin** [comment]
pending close

**Comment by michaelchin** [comment]
wait until 10 July, 2024 for Ben's return

**Comment by brmather** [comment]
This is working correctly for me now, but I wonder if we should keep this open until we test the notebooks / John releases the next version of pyGPlates with parallel support...?

**Comment by michaelchin** [comment]
> This is working correctly for me now, but I wonder if we should keep this open until we test the notebooks / John releases the next version of pyGPlates with parallel support...?

Testing the notebooks will be tracked in new issue https://github.com/GPlates/gplately/issues/223
