### ISSUE TITLE
Some PTT comments do not agree with pdoc3

### ISSUE THREAD

**Issue by michaelchin** [GPlates/gplately#201]
<img width="531" alt="Screenshot 2024-06-24 at 6 13 31 PM" src="https://github.com/GPlates/gplately/assets/2688316/8e950990-09f3-41dc-902d-b13f893f656b">

**Comment by michaelchin** [comment]
I will use "#" to replace ''' for the license declaration. See the screenshot below.

@GPlates/gplately-dev any concerns?

<img width="948" alt="Screenshot 2024-06-25 at 1 01 50 PM" src="https://github.com/GPlates/gplately/assets/2688316/d4d1eb89-061f-4c06-a109-de795f5474a8">

**Comment by michaelchin** [comment]
I will wait comments and objections for 3 days before starting to change all license statements in the source code.

**Comment by jcannon-gplates** [comment]
> I will use "#" to replace ''' for the license declaration

Thanks, yes I agree.

**Comment by michaelchin** [comment]
fixed in 03f7540
