### ISSUE TITLE
various issues with gplately

### ISSUE THREAD

**Issue by michaelchin** [GPlates/gplately#256]
These issues were reported by HS. Need triage first.

_check the screenshot in the shared folder named 'Movie_Gplately_Python.' For instance, at 1800 Ma, the subduction teeth are visible in a weird way, and around 1200 Ma, despite having a PlateID, aren't moving._

_It's strange because everything seems fine when using the GPlates software, as seen in the folder named 'Movie_Gplate_Software.'_

**Comment by michaelchin** [comment]
<img width="1310" alt="Screenshot 2024-08-15 at 2 24 12 PM" src="https://github.com/user-attachments/assets/9a628a1e-5a69-4dc9-b430-828e85baa018">

**Comment by michaelchin** [comment]
<img width="1343" alt="Screenshot 2024-08-15 at 2 51 38 PM" src="https://github.com/user-attachments/assets/a66f3570-81c1-4f0d-b582-d82795811ae2">
<img width="1461" alt="Screenshot 2024-08-15 at 2 52 07 PM" src="https://github.com/user-attachments/assets/0bf44963-76c0-42cf-a453-f6052c3ba9fb">

**Comment by michaelchin** [comment]
I opened the data file in GPlates and saw more points. Need more info from clients.

<img width="1132" alt="Screenshot 2024-08-15 at 2 59 29 PM" src="https://github.com/user-attachments/assets/1d53e9ff-c63e-4084-9861-48e0eab62eff">

**Comment by michaelchin** [comment]
after triage, this issue should be split into small, actionable issues. This issue may contain multiple problems and the description for these problems are very unclear.

**Comment by michaelchin** [comment]
![thumbnail_Rift_Deposits_1020](https://github.com/user-attachments/assets/309d1ef0-a286-4b6e-837d-020002508180)

**Comment by michaelchin** [comment]
@Hojat-Shirmard

_These points do not move after around 1000 Ma._

According to description above, it is very likely that the plate ID has no rotation definition after 1000Ma. See an example in the screenshot below.

<img width="1140" alt="Screenshot 2024-08-15 at 4 35 41 PM" src="https://github.com/user-attachments/assets/1c0dee77-f68e-42d6-9303-6ed06827a4a1">

**Comment by michaelchin** [comment]
If the plate ID is 16107. It will stop moving at 610Ma in the "1.8G model".

**Comment by michaelchin** [comment]
It is very likely that the points were not moving is not a gplately problem. Waiting for HS to confirm.

**Comment by Hojat-Shirmard** [comment]
Give me some time to write a script that tracks the points over time to identify those that don't move.

Cheers,
Hojat

________________________________

**Comment by michaelchin** [comment]
You can just compare the coordinates before and after reconstruction. If the rotation is not defined at some age, the coordinates should be the same. It is very likely the rotation is undefined for the plate i d beyond a certain age.

**Comment by michaelchin** [comment]
According to HS' email, it seemed that the "points not moving" was not a gplately bug at all.

Now the only remaining problem in this issue is the plate boundary plotting problem. It might be related to #191. I have asked HS to try the code change in the "191-plotting-artefacts-in-orthographic-projection" branch to see if it has the same root cause. 

Once confirmed, this issue can be closed as duplicate.

**Comment by michaelchin** [comment]
@Hojat-Shirmard 

Checkout "191-plotting-artefacts-in-orthographic-projection" branch and install gplately from the source code. See the instructions in the link below.

https://github.com/GPlates/gplately?tab=readme-ov-file#2-using-pip

**Comment by Hojat-Shirmard** [comment]
Yes, sure. Many thanks!

Cheers,
Hojat
________________________________

**Comment by michaelchin** [comment]
Have #161  and #160 fixed the "subduction teeth" problem? Can I close this issue?

**Comment by Hojat-Shirmard** [comment]
Not yet!
________________________________

**Comment by michaelchin** [comment]
Can I close this issue now?

**Comment by Hojat-Shirmard** [comment]
Yes sure. Thank you again!
