### ISSUE TITLE
agegrid cmdline - continents file inclusion instructions

### ISSUE THREAD

**Issue by RichardScottOZ** [GPlates/gplately#275]
Just tried the current repo version.

There is a 'None' default in the continents -c parameter.

If you have no '-c' with a correct file, this crashes.
 
Should put in the help this is mandatory in that case?  Obvious to the initiated probably - but a None default doesn't make it so for the new person.

**Comment by michaelchin** [comment]
I need a RA to help me with this.

**Comment by michaelchin** [comment]
maybe @Hojat-Shirmard can look into this.

This is a serious software defect. No matter what users do, the software program should not crash.

**Comment by Hojat-Shirmard** [comment]
I’d be happy if could help you with that. I’m heading to Hobart for a conference this Sunday and will be back on Monday, October 21.
