### ISSUE TITLE
add requires-python = ">= 3.8" to pyproject.toml

### ISSUE THREAD

**Issue by michaelchin** [GPlates/gplately#285]
The release of Python version 3.6 introduced formatted string literals, simply called “f-strings.” GPlately uses  “f-strings.” Python before 3.6 would not work.

**Comment by michaelchin** [comment]
In fact, it should be requires-python = ">= 3.8" because pygplates supports >= 3.8

**Comment by jcannon-gplates** [comment]
Yes I just compile the [currently supported](https://devguide.python.org/versions/) Python versions, for pyGPlates.

**Comment by michaelchin** [comment]
yes, can we drop python3.9 as well. I would like to have https://peps.python.org/pep-0585/

**Comment by michaelchin** [comment]
Sorry, I meant 3.8 in above comment.

**Comment by jcannon-gplates** [comment]
Yeah I guess 3.8 supports ends this month. I'll probably keep 3.8 for this pygplates release since I'm not (yet?) using type hints.

I haven't really thought about type hints much - do you run an off-line type checker over GPlately, or something like that?

**Comment by michaelchin** [comment]
> Yeah I guess 3.8 supports ends this month. I'll probably keep 3.8 for this pygplates release since I'm not (yet?) using type hints.
> 
> I haven't really thought about type hints much - do you run an off-line type checker over GPlately, or something like that?

vscode + pylance???

**Comment by jcannon-gplates** [comment]
Looks nifty - yeah vscode is pretty cool with all those extensions.

**Comment by michaelchin** [comment]
@GPlates/gplately-dev any concerns/comments/objections/compliments about adding  ""requires-python = ">= 3.8"""

If there is no formal/informal protests in 7 days, I will add  ""requires-python = ">= 3.8"""
