### ISSUE TITLE
Cannot find variable (z) data in netcdf

### ISSUE THREAD

**Issue by nickywright** [GPlates/gplately#287]
GPlately seems to only read netcdfs that has its data variable called `z`.

E.g. I have this netcdf:
<img width="764" alt="Screenshot 2024-10-11 at 6 17 13 pm" src="https://github.com/user-attachments/assets/769a5469-426b-4577-87a1-f2c1091e0b5f">

And when importing into gplately, I get:
<img width="1018" alt="Screenshot 2024-10-11 at 6 20 43 pm" src="https://github.com/user-attachments/assets/71088759-8f55-40a5-9edf-ceccec742433">

If I then rename the variable `topo` to `z`, it all works fine:
<img width="1038" alt="Screenshot 2024-10-11 at 6 26 27 pm" src="https://github.com/user-attachments/assets/4afc71a0-debb-4e72-baf2-377bf1a15146">

Is there a way we can GPlately read netcdfs that do not always have 'z' as variable names?

**Comment by michaelchin** [comment]
I agree that maybe we need a better way to deal with the data variable name. See the relevant code below.

https://github.com/GPlates/gplately/blob/da56af8a6fac13b02f1ba1c26cd206704654443a/gplately/grids.py#L203-L206

**Comment by michaelchin** [comment]
also maybe consider multiple data variables

**Comment by michaelchin** [comment]
This is an important issue. We need to provide a proper solution. But I have no time right now. Maybe @Hojat-Shirmard can have a look next week?

**Comment by Hojat-Shirmard** [comment]
I’d be happy if could help you with that. I’m heading to Hobart for a conference this Sunday and will be back on Monday, October 21.

**Comment by michaelchin** [comment]
> I’d be happy if could help you with that. I’m heading to Hobart for a conference this Sunday and will be back on Monday, October 21.

Sure. no rush, no pressure. any time that is convenient for you. safe trip.

**Comment by michaelchin** [comment]
@nickywright 

The latest master branch should work now. See the test notebook below.

https://gist.github.com/michaelchin/ef0ec6184c8195065c130050a2075c2c
