### ISSUE TITLE
Specify anchor plate

### ISSUE THREAD

**Issue by dansand** [GPlates/gplately#47]
Is it possible to create animations with a different fixed plate? I have done this pygplates, where the `resolve` and `reconstruct`  functions take an "anchor plate Id" argument. However, it doesn't seem like these are exposed to the `PlateReconstruction` class  in gplately?

**Comment by brmather** [comment]
Hi @dansand - sorry for not getting back to you sooner! Hope you're well. Can you clarify if you still have this issue? There is an `anchor_plate_id` keyword in the `reconstruct` option on the `PlateReconstruction` object. Or is your problem mostly to do with plotting?
