### ISSUE TITLE
Unzip error for etopo grid

### ISSUE THREAD

**Issue by brmather** [GPlates/gplately#57]
Hi @lauren-ilano @laurilano 

I get the following error message:

![Screenshot 2022-11-30 at 4 52 33 pm](https://user-images.githubusercontent.com/15915881/204718508-987519d1-e096-4b9f-a848-da76bf16f132.png)

**Comment by laurilano** [comment]
Hi @brmather,
I just pushed a fix to read .grd rasters downloaded with `get_raster` using gplately.Raster instead of imread.
