### ISSUE TITLE
plot_subduction_teeth

### ISSUE THREAD

**Issue by thomas-schouten** [GPlates/gplately#86]
Hi,

I am using GPlately to plot my tectonic reconstruction. I downloaded GPlately today, so I have the latest version of GPlately and pyGPlates. I have a topological closed plate polygon with subduction zones loaded as a pgyplates feature collection. All subduction zone segments have a polarity. I am able to plot trenches, ridges, faults without problem. However, I am unable to plot the subduction teeth, even though I receive no error message. 

Sample code:
`fig, ax = plt.subplots(subplot_kw={'projection': cartopy.crs.PlateCarree()}, figsize=(12, 8))`
`ax.set_extent([50, 105, -10, 40], crs=cartopy.crs.PlateCarree())`
`plate_model = gplately.PlateReconstruction(rotation_model, plates)`
`plot_plates = gplately.plot.PlotTopologies(plate_model, time)`
`plot_plates.time = i`
`plot_plates.plot_ridges_and_transforms(ax, color="r")`
`plot_plates.plot_trenches(ax, color="b")`
`plot_plates.plot_faults(ax, color="k")`
`plot_plates.plot_subduction_teeth(ax, color="k")`

![image](https://user-images.githubusercontent.com/130984647/232485077-89305a32-90df-47f8-80f7-c10160ea0bd3.png)

What could be the issue?

Many thanks,
Thomas Schouten

**Comment by michaelchin** [comment]
The size of triangles is in meters. But the lines are in degrees. The mismatch in measure units caused no triangle has been plotted.

**Comment by michaelchin** [comment]
fixed in 1d60b76
<img width="773" alt="Screenshot 2023-10-10 at 5 14 22 pm" src="https://github.com/GPlates/gplately/assets/2688316/86a8bf4f-b31a-43ba-bcb1-c64ef5c0b8a0">

**Comment by brmather** [comment]
@michaelchin we need to update the notebooks in case the subduction teeth have changed. Perhaps @lauren-ilano @laurilano can re-run the notebooks to make sure everything works...?
