### ISSUE TITLE
Deforming network geometries

### ISSUE THREAD

**Issue by taschaap** [GPlates/gplately#90]
Howdy everyone, and well done on this very cool project.

I'm just putting this here as a feature request: I have a model full of deforming network features and I would love to plot their boundary geometries like any other polygon, but as far as I can tell, gplately will only reconstruct _points_ within the network (example shapely multipoint geometry shown).

Is there currently a workaround for this? I admittedly haven't been playing with this for long.

![image](https://user-images.githubusercontent.com/79949261/233762765-38f8df68-92aa-4582-a782-dfaccf60fe82.png)

**Comment by brmather** [comment]
Hi @taschaap 👋 

Thanks for using GPlately.

I believe the deforming networks can be accessed as follows:

```python
gpd = gplot.get_all_topologies() # geopandas dataframe
gpd_network = gpd[gpd['feature_name'] == 'TopologicalNetwork'] # subset of all topologies
gpd_network.plot(ax=ax, transform=gplot.base_projection) # plot on axes
```

where `gplot` is a `gplately.PlotTopologies` object. I haven't tested this extensively, but perhaps you could see if it works for your topologies and compare it against those rendered in GPlates?

**Comment by michaelchin** [comment]
waiting for customer's feedback
