### ISSUE TITLE
Download performance benchmark

### ISSUE THREAD

**Issue by michaelchin** [GPlates/gplately#96]
Run the following code on my macbook at home at 10:45am on Tue 13 Jun 2023.

    gdownload = gplately.download.DataServer("Muller2019")
    (
        rotation_model,
        topology_features,
        static_polygons,
    ) = gdownload.get_plate_reconstruction_files()
    coastlines, continents, COBs = gdownload.get_topology_geometries()

time: 21.179454803466797
process time: 10.159185

The size of download file is 44MB. My internet is >90Mbps. But the download speed is 4-5Mbps. It means the server's network is slow.

Run the test script again. Even when the files are up-to-date, it still took 10 seconds to finish. Something is wrong.

    Checking whether the requested files need to be updated...
    Requested files are up-to-date!
    Checking whether the requested files need to be updated...
    Requested files are up-to-date!
    time: 10.715551853179932
    process time: 7.444118

**Comment by brmather** [comment]
This is pretty slow. If you run it again, it is still slow even though the files are cached because of the checks to find the latest version.
