### ISSUE TITLE
io.py conflicts with system Lib io

### ISSUE THREAD

**Issue by michaelchin** [GPlates/gplately#98]
@brmather @cpalfonso @laurilano 
Shall we rename the file?

**Comment by brmather** [comment]
How does this conflict?

**Comment by michaelchin** [comment]
> How does this conflict?

It would be better if we can avoid this kind of file names if possible.

<img width="1179" alt="Screenshot 2023-07-05 at 7 56 51 pm" src="https://github.com/GPlates/gplately/assets/2688316/5b775911-d3c1-47d4-965f-2f0e39cd342e">

**Comment by brmather** [comment]
Ah yes, makes sense to rename it.

**Comment by michaelchin** [comment]
fixed in [c5ebdea](https://github.com/GPlates/gplately/commit/c5ebdeab26536b86ed41bd98cce43dd6048865ac)
